Fri Sep  9 07:54:52 2022 - INFO  - Start to prepare the test environment.
Fri Sep  9 07:55:42 2022 - ERROR - You need to check the environment configuration file to see if this node information exists.
Traceback (most recent call last):
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 168, in <module>
    exitcode, output = rpm_install(args.pkgs, args.node, args.tempfile)
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 66, in rpm_install
    conn = ssh_cmd.pssh_conn(
  File "/root/GitRepo/mugen-riscv/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 340, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/usr/lib/python3.10/site-packages/paramiko/client.py", line 203, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib64/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
Fri Sep  9 07:55:48 2022 - ERROR - You need to check the environment configuration file to see if this node information exists.
Fri Sep  9 07:55:48 2022 - INFO  - End to prepare the test environment.
Fri Sep  9 07:55:49 2022 - INFO  - Start to run test.
traceroute to localhost (::1) from ::1, port 7, from port 63597, 30 hops max, 60 bytes packets
7 port 80: Address family for hostname not supported
Fri Sep  9 07:55:50 2022 - ERROR - oe_test_ndisc6_tcptraceroute6.sh line 31
 1  localhost (::1)  0.514 ms [open]  0.309 ms  0.296 ms 
traceroute to localhost (::1) from ::1, port 7, from port 63590, 30 hops max, 50 bytes packets
traceroute to localhost (::1) from ::1, port 7, from port 63588, 30 hops max, 60 bytes packets
 1  localhost (::1)  0.454 ms [open]  0.281 ms  0.279 ms 
traceroute6: TCP & UDP IPv6 traceroute tool 1.0.4 ($Rev$)
Usage: tcptraceroute6 [options] <IPv6 hostname/address> [port number]
Fri Sep  9 07:55:52 2022 - INFO  - End to run test.
Fri Sep  9 07:55:53 2022 - ERROR - failed to execute the case.
Fri Sep  9 07:55:53 2022 - INFO  - Start to restore the test environment.
Fri Sep  9 07:56:09 2022 - INFO  - End to restore the test environment.
