Mon Sep 12 18:30:46 2022 - INFO  - Start environmental preparation.
Mon Sep 12 18:31:31 2022 - INFO  - End of environmental preparation!
Mon Sep 12 18:31:31 2022 - INFO  - Start testing...
Failed to restart plymouth-reboot.service: Unit plymouth-reboot.service not found.
Mon Sep 12 18:31:32 2022 - ERROR - plymouth-reboot.service restart failed
Mon Sep 12 18:31:33 2022 - ERROR - ../common/common_lib.sh line 34
Unit plymouth-reboot.service could not be found.
Mon Sep 12 18:31:39 2022 - ERROR - plymouth-reboot.service restart failed
Mon Sep 12 18:31:40 2022 - ERROR - ../common/common_lib.sh line 37
Failed to stop plymouth-reboot.service: Unit plymouth-reboot.service not loaded.
Mon Sep 12 18:31:41 2022 - ERROR - plymouth-reboot.service stop failed
Mon Sep 12 18:31:42 2022 - ERROR - ../common/common_lib.sh line 39
Unit plymouth-reboot.service could not be found.
Mon Sep 12 18:31:48 2022 - ERROR - plymouth-reboot.service stop failed
Mon Sep 12 18:31:49 2022 - ERROR - ../common/common_lib.sh line 42
Failed to start plymouth-reboot.service: Unit plymouth-reboot.service not found.
Mon Sep 12 18:31:49 2022 - ERROR - plymouth-reboot.service start failed
Mon Sep 12 18:31:50 2022 - ERROR - ../common/common_lib.sh line 44
Unit plymouth-reboot.service could not be found.
Mon Sep 12 18:31:57 2022 - ERROR - plymouth-reboot.service start failed
Mon Sep 12 18:31:57 2022 - ERROR - ../common/common_lib.sh line 47
Failed to get unit file state for plymouth-reboot.service: No such file or directory
Mon Sep 12 18:31:58 2022 - INFO  - Unit is indirect, ignoring.
Failed to start plymouth-reboot.service: Unit plymouth-reboot.service not found.
Mon Sep 12 18:31:59 2022 - ERROR - Job type reload is not applicable for unit plymouth-reboot.service
Mon Sep 12 18:32:00 2022 - ERROR - ../common/common_lib.sh line 91
Unit plymouth-reboot.service could not be found.
Unit plymouth-reboot.service could not be found.
Mon Sep 12 18:32:01 2022 - INFO  - Finish test!
Mon Sep 12 18:32:01 2022 - ERROR - failed to execute the case.
Mon Sep 12 18:32:02 2022 - INFO  - start environment cleanup.
Failed to stop plymouth-reboot.service: Unit plymouth-reboot.service not loaded.
Traceback (most recent call last):
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 144, in rpm_remove
    with open(tmpfile, "r") as f:
OSError: [Errno 36] File name too long: "Last metadata expiration check: 0:09:24 ago on Mon 12 Sep 2022 06:22:05 PM CST.\nError: \n Problem: conflicting requests\n  - nothing provides system-logos needed by plymouth-0.9.5-4.oe2209.riscv64\n(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)"
Mon Sep 12 18:32:05 2022 - INFO  - Finish environment cleanup!
