Fri Sep  9 02:39:52 2022 - INFO  - Start to prepare the test environment.
Fri Sep  9 02:40:11 2022 - INFO  - Finish preparing the test environment.
Fri Sep  9 02:40:11 2022 - INFO  - Start to run test.
usage: dnf install [-c [config file]] [-q] [-v] [--version]
usage: dnf install [-c [config file]] [-q] [-v] [--version]
help                      display a helpful usage message
Warning: failed loading '/etc/yum.repos.d/openEuler.repo', skipping.
usage: dnf [options] COMMAND
help                      display a helpful usage message
display a helpful usage message
Warning: failed loading '/etc/yum.repos.d/openEuler.repo', skipping.
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
Warning: failed loading '/etc/yum.repos.d/openEuler.repo', skipping.
    17 | -y install tree          | 2022-09-09 02:34 | Install        |    1   
    14 | -y install tree          | 2022-09-09 02:28 | Install        |    1   
     7 | -y install tree          | 2022-09-09 02:19 | Install        |    1   
Warning: failed loading '/etc/yum.repos.d/openEuler.repo', skipping.
Error: No matching Packages to list
Fri Sep  9 02:40:58 2022 - ERROR - oe_test_dnf_help_history_info.sh line 43
Fri Sep  9 02:40:58 2022 - INFO  - End of the test.
Fri Sep  9 02:40:59 2022 - ERROR - failed to execute the case.
Fri Sep  9 02:41:00 2022 - INFO  - Start to restore the test environment.
Traceback (most recent call last):
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py", line 144, in rpm_remove
    with open(tmpfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Warning: failed loading \'/etc/yum.repos.d/openEuler.repo\', skipping.\nError: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".'
Fri Sep  9 02:41:03 2022 - INFO  - Finish restoring the test environment.
